name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "y1m.dpdns.org"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.y1m.dpdns.org", custom_domain = true },
  { pattern = "quay.y1m.dpdns.org", custom_domain = true },
  { pattern = "gcr.y1m.dpdns.org", custom_domain = true },
  { pattern = "k8s-gcr.y1m.dpdns.org", custom_domain = true },
  { pattern = "k8s.y1m.dpdns.org", custom_domain = true },
  { pattern = "ghcr.y1m.dpdns.org", custom_domain = true },
  { pattern = "cloudsmith.y1m.dpdns.org", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
